/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author Honorio Acosta Ruiz
 */
public class Pizarra extends javax.swing.JFrame implements Runnable {

	/**
	 * Creates new form Pizarra
	 */
	public Pizarra() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    leftPanel = new javax.swing.JPanel();
    lblTitleFiguras = new javax.swing.JLabel();
    jToggleButton1 = new javax.swing.JToggleButton();
    centerPanel = new javax.swing.JPanel();
    rightPanel = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Pizarra");
    setName("mainView"); // NOI18N
    setResizable(false);

    leftPanel.setOpaque(false);
    java.awt.GridBagLayout leftPanelLayout = new java.awt.GridBagLayout();
    leftPanelLayout.columnWidths = new int[] {0, 10, 0};
    leftPanelLayout.rowHeights = new int[] {0, 10, 0};
    leftPanel.setLayout(leftPanelLayout);

    lblTitleFiguras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblTitleFiguras.setText("Figuras");
    lblTitleFiguras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    leftPanel.add(lblTitleFiguras, new java.awt.GridBagConstraints());

    jToggleButton1.setText("jToggleButton1");
    jToggleButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
    jToggleButton1.setMargin(new java.awt.Insets(12, 14, 2, 14));
    leftPanel.add(jToggleButton1, new java.awt.GridBagConstraints());

    getContentPane().add(leftPanel, java.awt.BorderLayout.WEST);

    centerPanel.setBackground(new java.awt.Color(255, 255, 255));
    getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);
    getContentPane().add(rightPanel, java.awt.BorderLayout.EAST);

    pack();
  }// </editor-fold>//GEN-END:initComponents

	@Override
	public void run() {
		setSize(1100, 700);
		setLocationRelativeTo(null);
		setVisible(true);
	}

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel centerPanel;
  private javax.swing.JToggleButton jToggleButton1;
  private javax.swing.JLabel lblTitleFiguras;
  private javax.swing.JPanel leftPanel;
  private javax.swing.JPanel rightPanel;
  // End of variables declaration//GEN-END:variables
}
